blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace= 'catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='название')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='превью', **NULLABLE)
    date_of_creation = models.DateField(verbose_name='дата создания', **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = 'блоговая запись'
        verbose_name_plural = 'блоговые записи'

blog/views.py
from django.urls import reverse_lazy, reverse

from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(CreateView):
    """Контроллер создания статьи (после создания переходим на вкладку Блог"""
    model = Blog
    fields = ('title', 'body', 'preview', 'date_of_creation', 'is_published',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        """Формируем динамический slug-name"""

        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

class BlogListView(ListView):
    """Контроллер для вывода списка статей блога"""
    model = Blog

    """Контроллер для вывода в список статей только те, 
    которые имеют положительный признак публикации"""
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

class BlogDetailView(DetailView):
    """Контроллер для вывода детальной информации о статье"""
    model = Blog

    def get_object(self, queryset=None):
        """Изменение счетчика просмотра статьи"""
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object

class BlogUpdateView(UpdateView):
    """Контроллер для редактирования статьи"""
    model = Blog
    fields = ('title', 'body', 'preview', 'date_of_creation', 'is_published',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        """Формируем динамический slug-name"""

        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])

class BlogDeleteView(DeleteView):
    """Контроллер для удаления статьи"""
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить материал "{{ object.title}}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>

</div>


{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="cart-header">
                    <h3 class="card-title">
                        Статья "{{blog.title}}" ({{ blog.slug }})
                    </h3>
                </div>
                <div class="card-body">
                    <img src="{{ blog.preview|mediapath }}" class="img-fluid" alt="{{ blog.title }}">
                    <div class="col-md-8 mb-3">
                        <p>
                            {{ blog.body }}
                        </p>
                    </div>
                </div>
                <div class="card-footer">
                    Просмотры: {{ blog.views_count }}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<br>
<h1 align="center">Добавление новой статьи</h1><br><br>
<div class="row"><br>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>

                </form>
            </div>
        </div>
    </div>

</div>


{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore - блог</h1>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить статью</a>
</div>
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">
                    {{ object.title }}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'blog:view' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">View</a>
                        <a href="{% url 'blog:edit' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="{% url 'blog:delete' object.pk %}"
                           class="btn btn-sm btn-outline-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endfor %}

{% endblock %}