blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace= 'catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, VerificationTemplateView, generate_new_password, \
    ErrorVerificationTemplateView

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verify_email/', VerificationTemplateView.as_view(), name='verify_email'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('verify_email/error/', ErrorVerificationTemplateView.as_view(), name='verify_email_error'),
]

users/models.py
import random

from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}

code = ''.join([str(random.randint(0, 9)) for _ in range(12)])

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='страна', **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name='Активность')
    email_verified = models.BooleanField(default=False, verbose_name='Верификация почты')

    ver_code = models.CharField(max_length=15, default=code, verbose_name='Проверочный код')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f' {self.email}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:verify_email')

    def form_valid(self, form):
        if form.is_valid():
            new_user = form.save()
            send_mail(
                subject='Подтверждение почты',
                message=f'Код {new_user.ver_code}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[new_user.email]
            )
        return super().form_valid(form)


class VerificationTemplateView(TemplateView):
    template_name = 'users/msg_email.html'

    def post(self, request):
        ver_code = request.POST.get('ver_code')
        user_code = User.objects.filter(ver_code=ver_code).first()

        if user_code is not None and user_code.ver_code == ver_code:
            user_code.is_active = True
            user_code.save()
            return redirect('users:login')
        else:
            return redirect('users:verify_email_error')


class ErrorVerificationTemplateView(TemplateView):
    template_name = 'users/verify_email.html'
    success_url = reverse_lazy('users:msg_email')

class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('catalog:home'))

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content%}
    <div class="col-12 m-3">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3> Вход </h3>
                    </div>
                    <div class="body m-3">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button  type="submit" class="btn btn-success m-3">
                               Войти
                            </button>

                    <div class="card-footer"></div>

                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/msg_email.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-4"></div>
          <div class="col-4">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Введите код
                </h4>
              </div>
              <div class="card-body">
                  {% csrf_token %}

                  <input type="text" name="ver_code" class="form-control" id="ver_code" required>
              </div>
              <div class="card-footer">
                  <button type="submit" class="btn btn-success">Подтвердить</button>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content%}
    <div class="col-12 m-3">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3> Регистрация </h3>
                    </div>
                    <div class="body m-3">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button  type="submit" class="btn btn-success m-3">
                               Регистрация
                            </button>

                    <div class="card-footer"></div>

                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content%}
    <div class="col-12 m-3">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3> Профиль </h3>
                    </div>
                    <div class="body m-3">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <a class="btn btn-secondary btn-sm" href="{% url 'users:generate_new_password' %}" >Восстановить пароль</a>

                    </div>
                    <div class="card-footer">
                        <button  type="submit" class="btn btn-success m-3">
                               Сохранить
                            </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/verify_email.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-4"></div>
          <div class="col-4">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Неверный код
                </h4>
              </div>
              <div class="card-body">
              </div>
              <div class="card-footer">
                  <a href="{% url 'users:verify_email' %}" class="btn btn-success">Повторить попытку</a>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}