blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig

from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace= 'catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}

class Category(models.Model):
    objects = None
    category = models.CharField(max_length=100, verbose_name='категория')
    description_category = models.CharField(max_length=200, verbose_name='описание')

    def __str__(self):
        return f'{self.category}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    objects = None
    name = models.CharField(max_length=100, verbose_name='название')
    description_product = models.CharField(max_length=500, verbose_name='описание')
    image = models.ImageField(upload_to='image/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория', null=True)
    price = models.FloatField(verbose_name='цена за штуку')
    date_of_creation = models.DateField(verbose_name='дата создания', default=None, **NULLABLE)
    last_modified_date = models.DateField(verbose_name='дата последнего изменения', default=None, **NULLABLE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    number_version = models.IntegerField(verbose_name='номер_версии')
    name = models.CharField(max_length=100, verbose_name='название версии')
    current_version = models.BooleanField(default=True, verbose_name='признак_текущей_версии')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version
from config import settings


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        # fields = '__all__'
        fields = ('name', 'description_product', 'category', 'price',)
        # exclude = ('is_active',)

    def clean(self):

        cleaned_data = super().clean()
        name = cleaned_data.get('name').lower()
        description = cleaned_data.get('description_product').lower()

        if name and any(word in name for word in settings.FORBIDDEN_WORDS):
            self.add_error('name', 'Недопустимое слово в названии продукта!')

        if description and any(word in description for word in settings.FORBIDDEN_WORDS):
            self.add_error('description_product', 'Недопустимое слово в описании продукта!')

        return cleaned_data


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ('product', 'name', 'number_version', 'current_version',)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}): {message}')
    content = {
        'title': 'Контакты',
    }
    return render(request, 'catalog/contacts.html', content)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'catalog/product.html'


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        if form.is_valid:
            new_product = form.save()
            new_product.user = self.request.user
            new_product.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = 'catalog/product_delete.html'
    success_url = reverse_lazy('catalog:home')

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

  <title>{{ title }}</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/pricing/">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
<div class="container">
    <div class="row">
        {% block content%}
        {% endblock %}
    </div>


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted"><p>&copy; 2023 - {% now 'Y' %}</p></small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-lg-9 col-md-6 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <table class="table table-striped">
                <tr>
                    <td class="w-25">Страна</td>
                    <td>USA</td>
                </tr>
                <tr>
                    <td class="w-25">ИНН</td>
                    <td>91-1144442</td>
                </tr>
                <tr>
                    <td class="w-25">Адрес</td>
                    <td>Redmond,WA,98052-6399</td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="col-lg-3 col-md-6 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
        </div>
        <div class="card-body">
            <form method="post" >
                {% csrf_token %}
                <div class="mb-3">
                    <label for="name">Имя</label>
                    <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                </div>
                <div class="mb-3">
                    <label for="phone">Телефон</label>
                    <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                </div>
                <div class="mb-3">
                    <label for="message">Сообщение</label>
                    <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                </div>
                <input type="submit"  value="Отправить" />
            </form>

        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
</div>
{% for object in object_list %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{object.name|title}}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">{{object.price}} $</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{object.category}}</li>
                <li>{{object.description_product|truncatechars:10}}</li>
            </ul>
                    <a class="p-2 btn btn-outline-primary" href="product/{{object.id}}/">View</a>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:update_product' object.pk %}">Edit</a>
                    <a class="p-2 btn btn-outline-danger" href="{% url 'catalog:delete_product' object.pk %}">Delete</a>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-md-4">
    <img src="{{ product.image|mediapath }}" alt="">
</div>
<div class="col-md-8">
    <h2>{{ product.name }}</h2>
    <p>Категория: {{ product.category }}</p>
    <p>Описание товара: {{ product.description_product }}</p>
    <p>Цена: {{ product.price }} $</p>
    <button class="btn btn-primary">Купить</button>
</div>


{% endblock %}

catalog/templates/catalog/product_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
  <form method="post" enctype="multipart/form-data">
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h2 class="card-title">
            Удаление продукта {{ product.name }}
          </h2>
        </div>
        <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </div>
        <div class="card-footer">
          <a href="{% url 'catalog:home' %}" >Отмена</a>
        </div>
      </div>
    </div>

  </form>
</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
  <form method="post" enctype="multipart/form-data">
    <div class="col-6">
      <div class="card">
        <div class="card-header">
          <h2 class="card-title">
            Введите данные продукта
          </h2>
        </div>
        <div class="card-body">
          {% csrf_token %}
          {{ form.as_p }}
        </div>
        <div class="card-footer"></div>
      </div>
    </div>
    <div class="col-6">
      <div class="card">
        <div class="card-body">
           {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{form.as_p}}
                {% endfor %}
        </div>
        <div class="card-footer"></div>
      </div>
    </div>
    <button type="submit" class="btn btn-success">Сохранить</button>
  </form>
</div>

{% endblock %}